coffee_shop/urls.py
from collections import namedtuple
from django.contrib.auth import login
from django.urls import path
from django.views.generic.base import TemplateView
from coffee_shop import views
from coffee_shop.models import Order

app_name = 'coffee_shop'
urlpatterns = [
    path('', views.home_page, name="home-page"),
    path('products/', views.ProductListView.as_view(template_name="coffee_shop/products.html", paginate_by=5), name='products'),
    path('login/', views.login, name="login"),
    path('products/<int:pk>', views.product_detail,name='product_detail'),
    path('product/add-to-cart/<int:pk>',views.add_to_cart, name='add-to-cart'),
    path('product/reduce-from-cart/<int:pk>',views.reduce_from_cart, name='reduce-from-cart'),
    path('product/remove-from-cart/<int:pk>',views.remove_from_cart, name='remove-from-cart'), 
    path('product/increase-from-cart/<int:pk>', views.increase_from_cart, name='increase-from-cart'),
    path('check-out/', views.check_out, name='check-out'),
    ############################## Management view ############################
    path('manage/create-staff-account/', views.create_staff_account, name = 'create_staff_account'),
    ###### Products #######
    path('manage/products/', views.ProductListView.as_view(template_name="manage/product_list.html"), name="product_list"),
    path('manage/products/add-product/', views.ProductCreateView.as_view(template_name='manage/product_create.html'), name='add_product'),
    path('manage/product/edit-detail/<int:pk>', views.edit_product_detail, name='edit_product_detail'),
    path('manage/product/mark-deleted/<int:pk>', views.mark_product_deleted, name='mark_product_deleted'),
    path('manage/product/add-category/', views.CategoryCreateView.as_view(template_name="manage/category_create.html"), name="add_category"),
    path('manage/product/rename-category/<int:pk>', views.rename_category, name="rename-category"),
    ###### Orders ######
    path('manage/', views.manage_index, name = 'manage_index'),
    ###### List View ####
    path('manage/orders/', views.OrderListView.as_view(), name='order_list'),
    path('manage/orders/unconfirmed/', views.OrderListView.as_view(qs = Order.objects.filter(confirm=False, ordered=True).order_by('-ordered_date')), name='unconfirmed_order_list'),
    path('manage/orders/confirmed/', views.OrderListView.as_view(qs = Order.objects.filter(confirm=True, success=False).order_by('-ordered_date')), name='confirmed_order_list'),
    path('manage/orders/success/', views.OrderListView.as_view(qs = Order.objects.filter(success=True).order_by('-ordered_date')), name='success_order_list'),
    ###### Detail view ######
    path('manage/order/<int:pk>', views.OrderDetailView.as_view(template_name='manage/order_detail.html'), name='order_detail'),


    ###### Handling order #######
    path('manage/order/mark-confirm/<int:pk>', views.mark_confirm, name='order_mark_confirm'),
    path('manage/order/mark-success/<int:pk>', views.mark_success, name='order_mark_success'),
    path('manage/order/delete/<int:pk>', views.order_delete, name='order_delete'),
    # Sales #
    path('manage/sales/', views.sales, name='sales'),
    # Success message #
    path('manage/order-success-message/', views.order_success_message_edit, name="success-message-edit")
]   

first_django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coffee_shop.urls')),
    path('accounts/login/', views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coffee_shop/models.py
from io import open_code
from django.db import models
from django.db.models.fields import CharField, IntegerField, TextField
from django.db.models.fields.related import ManyToManyField
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
# Receive the pre_delete signal and delete the file associated with the model instance.
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

# Create your models here.
class Company(models.Model):
    sales = IntegerField(default = 0)
    orders = IntegerField(default = 0)
    success_order_title = CharField(max_length=200, default="Đặt hàng thành công")
    success_order_message = TextField(blank=True)


class SubCategory(models.Model):
    name = CharField(max_length=100, verbose_name="Tên loại cụ thể", unique=True)
    def __str__(self):
        return self.name


class Category(models.Model):
    name = CharField(max_length=100, verbose_name="Tên loại", unique=True)
    sub_categories = ManyToManyField(SubCategory, blank=True, verbose_name="Loại cụ thể")
    sales = IntegerField(default = 0)
    def get_rename_url(self):
        return reverse('coffee_shop:rename-category', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Topping(models.Model):
    description = models.CharField(max_length=50,verbose_name="Mô tả" )
    price = models.IntegerField(verbose_name="Giá")
    def __str__(self):
        return self.description


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name=('Tên sản phẩm'))
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=False, default=True, verbose_name="Loại")
    sub_category = models.CharField(max_length=100, blank=True, verbose_name=("Loại cụ thể"))
    topping = ManyToManyField(Topping, verbose_name="Topping", blank=True)
    description = models.TextField(blank=True, verbose_name=('Mô tả'))
    price = models.IntegerField(verbose_name=('Giá'))
    image = models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name=('Ảnh'))
    added_date = models.DateTimeField(default=timezone.now)
    deleted = models.BooleanField(default=False)
    def replace_image(self, *args, **kwargs):
        # delete old file when replacing by updating the file
        try:
            this = Product.objects.get(pk=self.pk)
            if this.image != self.image:
                this.image.delete(save=False)
        except: pass
        super(Product, self).save(*args, **kwargs)
    
    def add_option(self):
        return reverse('coffee_shop:add_product_option', kwargs={'pk': self.pk})

    def get_edit_product_detail_url(self):
        return reverse('coffee_shop:edit_product_detail', kwargs={'pk': self.pk})

    def get_mark_deleted_url(self):
        return reverse('coffee_shop:mark_product_deleted', kwargs={'pk': self.pk})

    def get_detail_view_url(self):
        return reverse('coffee_shop:product_detail', kwargs={'pk': self.pk})

    def get_add_to_cart_url(self):
        return reverse('coffee_shop:add-to-cart', kwargs={'pk': self.pk})

    def get_remove_from_cart_url(self):
        return reverse('coffee_shop:remove-from-cart', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class OrderProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    topping = ManyToManyField(Topping, blank=True)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)
    ip_address = models.CharField(max_length=50)
    
    def get_one_product_price(self):
        sum = self.product.price
        topping_list = self.topping.all()
        if topping_list:
            for topping in topping_list:
                sum += topping.price    
        return sum

    def get_price(self):
        sum = self.product.price
        topping_list = self.topping.all()
        if topping_list:
            for topping in topping_list:
                sum += topping.price    
        return sum * self.quantity
            
    def get_remove_from_cart_url(self):
        return reverse('coffee_shop:remove-from-cart', kwargs={'pk': self.pk})

    def get_reduce_from_cart_url(self):
        return reverse('coffee_shop:reduce-from-cart', kwargs={'pk': self.pk})
    
    def get_increase_from_cart_url(self):
        return reverse('coffee_shop:increase-from-cart', kwargs={'pk': self.pk})
    def get_topping_list(self):
        return self.topping.all()
    
    def get_original_name(self):
        return self.product.name
    
    def get_name(self):
        str = self.product.name
        if self.topping.all().exists():
            str += "("
            for topping in self.topping.all():
                if topping == self.topping.all().last():
                    str += topping.description
                else:
                    str += topping.description
                    str += " + "
            str += ")"
        return  str


    def __str__(self) -> str:
        str = f'{self.quantity} {self.product.name}'
        if self.topping.all().exists():
            str += "("
            for topping in self.topping.all():
                if topping == self.topping.all().last():
                    str += topping.description
                else:
                    str += topping.description
                    str += " + "
            str += ")"
        return  str


class Order(models.Model):
    name = models.CharField(max_length=40)
    phone_number = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    products = models.ManyToManyField(OrderProduct)
    ip_address = models.CharField(max_length=50)
    ordered = models.BooleanField(default=False)
    confirm = models.BooleanField(default=False)
    success = models.BooleanField(default=False)
    ordered_date = models.DateTimeField(default=timezone.now())
    total = IntegerField(default = 0)
    handler = models.CharField(max_length=100, blank=True)
    
    def get_mark_confirm_url(self):
        return reverse('coffee_shop:order_mark_confirm', kwargs={'pk': self.pk})

    def get_mark_shipping_url(self):
        return reverse('coffee_shop:order_mark_shipping', kwargs={'pk': self.pk})
    
    def get_mark_success_url(self):
        return reverse('coffee_shop:order_mark_success', kwargs={'pk': self.pk})
    
    def get_delete_url(self):
        return reverse('coffee_shop:order_delete', kwargs={'pk': self.pk})

    def get_unmark_cancel_url(self):
        return reverse('coffee_shop:order_unmark_cancel', kwargs={'pk': self.pk})

    def get_all_items_quantity(self):
        n = 0
        order_products = self.products.all()
        if order_products.exists():
            for order_product in order_products:
                n += order_product.quantity
        return n

    def get_total(self):
        price = 0
        for product in self.products.all():
            price += product.get_price()
        return price
    
    def get_ordered_products(self):
        return self.products.all()
    
    def get_detail_view_url(self):
        return reverse('coffee_shop:order_detail', kwargs={'pk': self.pk})

    def __str__(self) -> str:
        return self.name


class StaffInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    # Add any additional attributes you want
    phone_number = models.IntegerField()
    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

# Receive the pre_delete signal and delete the file associated with the model instance.

@receiver(pre_delete, sender=Product)
def product_delete(sender, instance, **kwargs):
    instance.image.delete(False)

coffee_shop/forms.py
from django import forms
from django.forms.fields import DateField
from .models import Product, StaffInfo, Category
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CategoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
    class Meta():
        model = Category
        fields = ('name',)
        
class ProductForm(forms.ModelForm):
    description = forms.CharField(label='Mô tả', widget=forms.Textarea(attrs={'id': "description", "class": "control-form"}))
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
    class Meta():
        model = Product
        exclude = ('added_date', 'topping', 'sub_category', 'deleted')




    
     


class OrderForm(forms.Form):
    name = forms.CharField(max_length=50, required=True, label='Tên người đặt hàng')
    phone_number = forms.CharField(max_length=15, required=True, label='Số điện thoại:')
    address = forms.CharField(max_length=200, required=True, label='Địa chỉ nhận hàng')

    def __init__(self, *args, **kwargs):
            super(OrderForm, self).__init__(*args, **kwargs)
            for visible in self.visible_fields():
                visible.field.widget.attrs['class'] = 'form-control'
    




class StaffForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2'] 
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Tài khoản'
        self.fields['username'].label=''
        self.fields['username'].help_text='<div class="form-text text-muted"><small>Bắt buộc. Chỉ bao gôm ký tự chữ, số và các ký tự đặc biệt @/./+/-/_ .</small></div>'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Mật khẩu'
        self.fields['password1'].label=''
        self.fields['password1'].help_text='<ul class="form-text text-muted small"><li>Mật khẩu của bạn cần ít nhất 6 ký tự.</li></ul>'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Xác nhận mật khẩu'
        self.fields['password2'].label=''
        self.fields['password2'].help_text=''

class StaffInfoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(StaffInfoForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
                visible.field.widget.attrs['class'] = 'form-control'
                self.fields['phone_number'].required = False
    class Meta():
        model = StaffInfo
        fields = ('phone_number',)
        labels = {
            'phone_number': 'Số điện thoại'
        }


class ImageForm(forms.Form):
    image = forms.ImageField(required=False, label="Ảnh")

class DateInput(forms.DateInput):
    input_type = "date"


class DateForm(forms.Form):
    start_date = forms.DateField(widget=DateInput, label="Từ", required=True)
    end_date = forms.DateField(widget=DateInput, label="Đến", required=True)

    def __init__(self, *args, **kwargs):
            super(DateForm, self).__init__(*args, **kwargs)
            for visible in self.visible_fields():
                visible.field.widget.attrs['class'] = 'form-control'

templates/coffee_shop/base.html
{% load static %}
{% load custom_template %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <!-- Latest compiled and minified css -->

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

 {# Custom CSS#}
  <link rel="stylesheet" href="{% static 'css/coffee.css' %}">
   <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title>Coffee Shop</title>
</head>
<body>
  <!-- Loader -->
  <div class="container">
    <div id="container-loader">
      <div class="loader"></div>
    </div>
      <nav  class="navbar navbar-expand-lg navbar-light bg-light">
        <div style="background: white; width: 100%; display:flex; padding: 10px;">
          <a class="navbar-brand" href="{% url 'coffee_shop:home-page' %}"><img src="{% static 'logo_pc.png' %}" alt=""></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            {% block home_page %}
            {% endblock %}
          </div>
          <ul style="margin: auto;" class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="#">Xin chào {{user.username}}</a>
            </li>
            {% if user.is_staff %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'coffee_shop:manage_index' %}">Quản lý</a>
            </li>
            {% endif %}
              <a class="nav-link" href="{% url 'logout'  %}">Đăng xuất</a>
            </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}"><h6>Đăng nhập</h6></a>
              </li>
              {% endif %}    
          </ul>
        </div>
       
      </nav>

    <!-- End - nav brand -->
    <div class="container sidebar">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav" style="margin: -10px;">
              {% for in_list_category in category_list %}
              {% if in_list_category == category %}
              <a style="background-color: black; color: white; " class="cat-btn link_class" aria-current="page" href="{% url 'coffee_shop:products' %}?category={{in_list_category}}"><h5><strong>{{in_list_category}}</strong></h5></a>
              {% else %}
              <a  class="cat-btn" aria-current="page" href="{% url 'coffee_shop:products' %}?category={{in_list_category}}"><h5><strong>{{in_list_category}}</strong></h5></a>
              {% endif %}
              {% endfor %}
            </div>
          </div>
          <a style="text-decoration: none;" href="{% url 'coffee_shop:check-out' %}">
            <div style="display: flex;" class="div">
              <span id="item_count" class="fa-stack red-cart fa-2x has-badge" data-count="{{order.get_all_items_quantity}}">
                <i class="fa fa-circle fa-stack-2x after-fa"></i>
                <i class="fa fa-shopping-cart fa-stack-1x fa-inverse after-fa"></i>
              </span>
            
              
              <div style="text-align: center; margin: auto;">
                {% if order %}
                <h6 id="total_price" style="color: red;">{{order.get_total|intcomma}}đ</h6>
                {% else %}
                <h6 id="total_price" style="color: red;"><strong>Giỏ hàng</strong></h6>
                {% endif %}
              </div>

            </div>
          </a>
      </nav>


      <div class="alert alert-success" id="success-alert"> 
          <strong id="popup-message">Bạn đã thêm thành công sản phẩm vào giỏ hàng</strong>
      </div>

    </div>
    
     
    {% block body_block %}
    {% endblock %}

    <!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <section
    class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
  >
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Contact
          </h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
  </div>

  <!-- Java script source -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>


<script>


// using jQuery get csrftoken from your HTML
var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

$.ajaxSetup({
    beforeSend: function (xhr, settings) {
        // if not safe, set csrftoken
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
    $(document).ready(function(){
        $('#Mybtn').click(function(){
              $('#MyForm').toggle(500);
      });
    });
  $(document).ready(function() {
    $("#container-loader").hide()
    $(".button, .close-btn").on('click', function() {
      $("#container-loader").fadeIn("").fadeOut("");
    })
});
  // Popup message
  $(document).ready(function() {
  $("#success-alert").hide();
  $(".add_product").click(function showAlert() {
    $("#success-alert").fadeTo(1000, 500).slideUp(500, function() {
      $("#success-alert").slideUp(500);
    });
  });
});
    // document.addEventListener("DOMContentLoaded", function(){
    //   window.addEventListener('scroll', function() {
    //       if (window.scrollY > 100) {
    //         document.getElementById('menu-nav').classList.add('fixed-top');
    //         // add padding top to show content behind navbar
    //         navbar_height = document.querySelector('.navbar').offsetHeight;
    //         document.body.style.paddingTop = navbar_height + 'px';
    //       } else {
    //         document.getElementById('menu-nav').classList.remove('fixed-top');
    //         // remove padding top from body
    //         document.body.style.paddingTop = '0';
    //       } 
    //   });
    // }); 
  var stickySidebar = $('.sidebar').offset().top;
  $(window).scroll(function() {
    if($(window).scrollTop() > stickySidebar) {
      $('.sidebar').addClass('fixed-top');
    }
    else {
      $('.sidebar').removeClass('fixed-top');
    }
  })

    function commafy( num ) {
    var str = num.toString().split('.');
    if (str[0].length >= 4) {
        str[0] = str[0].replace(/(\d)(?=(\d{3})+$)/g, '$1.');
    }
    if (str[1] && str[1].length >= 5) {
        str[1] = str[1].replace(/(\d{3})/g, '$1 ');
    }
    return str.join('.');
}
</script>
  {% block javascript %}
  {% endblock javascript %}


</body>
</html>

templates/coffee_shop/empty-cart.html
{% extends "coffee_shop/base.html" %}

{% block body_block %}
<div style="text-align:center; background:white; padding: 10%" class="container">
    <h1>Bạn không thể đặt hàng với giỏ hàng trống !</h1>
    <a style="color: black;" href=""><Strong>Quay lại trang sản phẩm</Strong></a>
</div>
{% endblock %}

templates/coffee_shop/success-message.html
{% extends "coffee_shop/base.html" %}

{% block body_block %}
<div style="background-color: white; text-align: center; padding: 10%;" class="container">
    <h1 style="color: rgb(255, 0, 0);">{{company.success_order_title}}</h1>
    <h4 style="color: rgb(255, 0, 0);">{{company.success_order_message}}</h4>
</div>  
{% endblock %}